---
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /manage
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
  security:
    enabled: false
